# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddc7b68d1e81fe19ac9c33afa000daf441225480458c7fc980e0ba35700bfb9ce7ff0f662f4bf737c3ff552e6750971a677ed7747ac874d4b0a9bc15244bd4b8

test:
  secret_key_base: 3b3098e836afab72f877e39279d509fd745ccada186fdb39b88bcea0cb2877fe2ef511657715940496d1ea15dfcbcdd2989cc6e2ab26252c66be4e2567a34752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
