# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75b497000917d46e46ed0cb413e99ece4b7f8774552cffa1e49180e0d65a34c1d02cf5747cec7a3fbdedb96d6d724e6b222f1551bfc9680bd1860fa8740593ed

test:
  secret_key_base: 7afefe3ed4e66fa99504ab40454e4a01ba2aec7f8f5a5a8d2588e8b22a9d4575bc963440da9b4a6217683d341256c1b177758e6ffe1421743681ea2ce8953a45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
