# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a0e02ee540b67d62af31411600277b4e35197d0b9fd84cc9e03fb4e28d2e76c51690a751d3655aaf63dae51853f78fb6636fcae90eaf3460b22b1ce5ac451a0

test:
  secret_key_base: 5be945377a4e41b7537cf2cbbee1eb27f73637623d084a219562e379513d777f9b89366751f31acf2da6784853faf6fc7671fed1477d16ea5a5eefba395db0a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
