# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8817db04e81d8bb3679fbf1eb479189865dc08f94d6b41a83c6a5340e3d3776953b3bf253d0b01e1270a0be3e9007cd33b20f5c5821fd6e5fee17f4c0b9cfae9

test:
  secret_key_base: 869806bf858b5aae2d67977cf8117b79809f07e623c29a5e76a0c8b1b6140c37907239edd8a3c48141e72bab089cadaab130788350ef14ef951a28e91effef9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
