# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e50ff18fc03a8e816242104facfca495f635a8c8e5c453f1258670ad9b529f84062ee0012a0fd21596b1907c007135fa030bc99f1c6ef93e69b51d70137e7e2

test:
  secret_key_base: 84896d011b7170d7a05f15b78c75b985ae1cd71f35bb37e4c208ea4fc07d10780b75799ac75c191f1b8edaa88d5416c2d68ad3940f8b8c8454f6d871a2640604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
