# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 867864d172a72b480f6852a9fd225df3ec01ac0387a10af8c88bb7eb542d821a45c110b0c15e6a12ff20eecd242eec6ef314c53369a7adab227d94e751b289ba

test:
  secret_key_base: 457471910bafc14061e50bcc21b220d74d00e490c0a45664ae8ad5d429d2489eab3a88482e9bd3a257e0088f6e23bc7eff722b8ace692a44e2c5a30a4ebcfbc6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
