# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de5c58873ea4d5a9830e99d06b400885757ac563c72a42244d32f746d5006e822a68006d47c91f848c499d6ef95236a991cba452a740e2e8f50692d8398531f3

test:
  secret_key_base: 8ba9d02773ea820fa8aacd929ab73d8f3849218697e3ce51dc34a9f5361c525e64fe6948aa3a2cd63036bc0d9ca158a2c2b2830f9ad56d40b66bb1405a357a9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
