default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password: developer
  pool: 5

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
