default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: showmojo_development

test:
  <<: *default
  database: showmojo_test
