# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be971fabb336c8b5a5db0f3f3effec9aeb6fbf0b253c6299f256fd1fe8ef68200297dc4045ac3bdf46c54328cb205897f0db795c4cb40a614c3d8f332fa3eef

test:
  secret_key_base: d798af05efd7e8ac57e9cd8ceb22e09530f553d935f5aff8f8581bbbb4150310a1a25cccd7e5d73bf37e6880c0887871e9df9049c09c86e02732d2641e93ba8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
