# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acc0790e972e8bafaae620de9d2c9252307cbb625becf272ee5fc56fe4f956ea1d1efae7c760a0bf5af469a78021b29004fdc8c9a4923edb1842d4a6debc6fb5

test:
  secret_key_base: ca1e3be410a3ff94ea4545af511aa92c3b769fccbd483c5111e9ed61ab08762b44cf3f37cf2bd1f983a0c3480d1296e2e4aba8b4456d2f173091182e1b28b271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
