# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 825e5cd3674e3b561cabdc67d843d27470682adc6cc0b6aa96a1bbb3c5cadf0d51e3c98b473a93b9c02cbfe413e5b0151e1001367a660dd9d9651c153f3b7a43

test:
  secret_key_base: 50886cb6a4fe1515b9cb5346171330b48e698747b3f88642bc303bf366bf9d1d1a745824a0abacb6a553a08b52092c0eba7ea60a0df5d52da48620a02c5551a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
