# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1631aa709fa0ea1641532126f08eb060cfe1aaa55df209e1ab8ff0537c45b38cd45f187b39d0747d8acfb9fcd743343136f4c4f502bafd5ba686519360761f56

test:
  secret_key_base: 19a9864cf7d4701a374cfa48ae883a9574b55ddda875eb72d3854be11869db923d0b7a800a9a95deb844292aaefc39f70eef6afd567e5315cf92a383347e2647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
