default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true
  resolved_paths: []
  cache_manifest: false
  extract_css: false
  extensions:
    - .js
    - .css

development:
  <<: *default
  compile: true
  check_yarn_integrity: true


test:
  <<: *default
  compile: true
  public_output_path: packs-test