# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6228c7972a6a10aec0e8e75b15cfc2acd99f6e036cfb61cf82f1bf22ffac3f5f89d2da788689c3ebcdf4b9230e718fd8873309e99d3ff904739846604f7d6249

test:
  secret_key_base: ae370616cfe22f68e40b21c79748daf64ed30e7095272f80f37678c511f1c697cb6579ae95b044824d60fde30e12e39c55ab4feb758181b702c2e229619d9c5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
