version: '3'
services:
  postgres:
    image: 'postgres:10.3-alpine'
    environment:
      POSTGRES_PASSWORD: developer
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  website:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - '.:/app'
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - postgres
volumes:
  postgres: {}
