AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - bin/setup

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - Gemfile

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - db/seeds.rb
    - spec/**/*_spec.rb
