source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'sqlite3'

gem 'sass-rails'
gem 'uglifier'
gem 'jquery-rails'

gem 'bootstrap-sass'

group :development, :test do
  gem 'pry'
  gem 'quiet_assets'
end

group :development do
  gem 'web-console'
  gem 'spring'
  gem 'meta_request'
end

group :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'database_cleaner'
end
