source 'https://rubygems.org'

gem 'rails', '4.2.11.1'
gem 'pg', '~> 0.20'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'draper'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
end

group :test do
  gem 'factory_bot_rails'
  gem 'capybara'
  gem 'shoulda-matchers'
end

group :development do
  gem 'spring'
end
