source 'https://rubygems.org'


gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'haml-rails'

group :development do
  gem 'web-console', '~> 2.0'
  gem 'byebug'
end

group :development, :test do
  gem 'spring'
  gem 'rspec-rails', '~> 3.5'
  gem 'factory_girl_rails'
  gem 'guard-rspec', require: false
  gem 'shoulda-matchers', '~> 3.1'
  gem 'capybara'
end

