source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'

gem 'haml'
gem 'bootstrap-sass'

group :development, :test do
  gem 'pry',                '~> 0.10.4'
  gem 'ffaker',             '~> 2.3'
  gem 'capybara',           '~> 2.10.1'
  gem 'poltergeist',        '~> 1.11.0'
  gem 'rspec-rails',        '~> 3.5.2'
  gem 'database_cleaner',   '~> 1.5.3'
  gem 'factory_girl_rails', '~> 4.7.0'
end

group :test do
  gem 'shoulda-matchers',   '~> 3.1.1'
end
